#!/usr/bin/env python3
"""Generate docker-compose.yml with a given number of PBS compute node services.

Compose's --scale/deploy.replicas can't give each replica a unique hostname or
container_name, which PBS nodes need (distinct hostname/pbsnodeN). Rather than
work around that at runtime, this script generates one explicit service per
node, matching the pbsnode[1-10] range the server pre-declares at startup
(raise the cap with PBS_MAX_NODES on the pbsserver service to go past 10).

Usage:
    ./generate-compose.py [--nodes N] [--output FILE]
"""
import argparse

HEADER = """# Generated by generate-compose.py --nodes {nodes}. Do not hand-edit the
# pbsnode service blocks below; re-run the script to change the node count.
x-node-common: &node-common
  image: ghcr.io/noaa-gsl/dockerspackstackpbscluster/pbs-spack-stack-mom:ubuntu-${{UBUNTU_VERSION:-26.04}}-spack-stack-${{SPACK_STACK_VERSION:-2.1.0}}
  shm_size: '4g'
  user: admin
  volumes:
    - home-vol:/home/admin
    - opt-vol:/opt/spack-stack:ro
  depends_on:
    pbsserver:
      condition: service_started
    pbsfrontend:
      condition: service_healthy
  healthcheck:
    test: ["CMD", "ssh", "-o", "StrictHostKeyChecking=no", "admin@localhost", "hostname"]
    interval: 10s
    timeout: 5s
    retries: 5

services:
  pbsfrontend:
    build:
      context: ./frontend
      args:
        SPACK_BUILD_JOBS: 8
        BASE_IMAGE_TAG: ubuntu-${{UBUNTU_VERSION:-26.04}}-openpbs-${{OPENPBS_VERSION}}
        UBUNTU_VERSION: ${{UBUNTU_VERSION:-26.04}}
        SPACK_STACK_VERSION: ${{SPACK_STACK_VERSION:-2.1.0}}
      secrets:
        - github_token
    image: ghcr.io/noaa-gsl/dockerspackstackpbscluster/pbs-spack-stack-frontend:ubuntu-${{UBUNTU_VERSION:-26.04}}-spack-stack-${{SPACK_STACK_VERSION:-2.1.0}}
    container_name: ${{CLUSTER_NAME:-spack-stack}}-frontend
    shm_size: '4g'
    hostname: pbsfrontend
    user: admin
    volumes:
      - home-vol:/home/admin
      - opt-vol:/opt/spack-stack
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/ssh-ready"]
      interval: 5s
      timeout: 2s
      retries: 250
      start_period: 60s

  pbsserver:
    build:
      context: ./server
      args:
        BASE_IMAGE_TAG: ubuntu-${{UBUNTU_VERSION:-26.04}}-openpbs-${{OPENPBS_VERSION}}
    image: ghcr.io/noaa-gsl/dockerspackstackpbscluster/pbs-spack-stack-server:ubuntu-${{UBUNTU_VERSION:-26.04}}-spack-stack-${{SPACK_STACK_VERSION:-2.1.0}}
    container_name: ${{CLUSTER_NAME:-spack-stack}}-server
    shm_size: '4g'
    hostname: pbsserver
    user: admin
    volumes:
      - home-vol:/home/admin
      - opt-vol:/opt/spack-stack:ro
    depends_on:
      pbsfrontend:
        condition: service_healthy
"""

FIRST_NODE_TEMPLATE = """
  pbsnode{n}:
    <<: *node-common
    build:
      context: ./mom
      args:
        BASE_IMAGE_TAG: ubuntu-${{UBUNTU_VERSION:-26.04}}-openpbs-${{OPENPBS_VERSION}}
    container_name: ${{CLUSTER_NAME:-spack-stack}}-node{n}
    hostname: pbsnode{n}
"""

NODE_TEMPLATE = """
  pbsnode{n}:
    <<: *node-common
    container_name: ${{CLUSTER_NAME:-spack-stack}}-node{n}
    hostname: pbsnode{n}
"""

FOOTER = """
volumes:
  home-vol:
  opt-vol:

secrets:
  github_token:
    environment: GITHUB_TOKEN
"""

MAX_NODES = 10


def build_compose(nodes: int) -> str:
    if not 1 <= nodes <= MAX_NODES:
        raise ValueError(f"--nodes must be between 1 and {MAX_NODES} "
                          f"(the PBS server pre-declares pbsnode[1-{MAX_NODES}])")
    parts = [HEADER.format(nodes=nodes)]
    parts.append(FIRST_NODE_TEMPLATE.format(n=1))
    parts.extend(NODE_TEMPLATE.format(n=i) for i in range(2, nodes + 1))
    parts.append(FOOTER)
    return "".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--nodes", type=int, default=5,
                         help="number of pbsnode services to generate (default: 5, max: %d)" % MAX_NODES)
    parser.add_argument("--output", default="docker-compose.yml",
                         help="output file path (default: docker-compose.yml)")
    args = parser.parse_args()

    compose = build_compose(args.nodes)
    with open(args.output, "w") as f:
        f.write(compose)

    print(f"Wrote {args.output} with {args.nodes} node service(s).")


if __name__ == "__main__":
    main()
